/**
 * AccessFix - Core Type Definitions & Interfaces
 *
 * Defines the contract for the core product flow:
 * User provides HTML -> Accessibility Scanner detects issues -> Findings are displayed
 * -> Repair Engine applies safe deterministic fixes -> Re-scan verifies repaired HTML
 * -> Before/After results displayed -> Relevant history stored in Firebase Firestore.
 */

export type SeverityLevel = 'critical' | 'serious' | 'moderate' | 'minor' | 'warning';

export type FindingCategory =
  | 'images'
  | 'forms'
  | 'structure'
  | 'aria'
  | 'contrast'
  | 'semantics'
  | 'navigation'
  | 'other';

export type FindingStatus =
  | 'detected'
  | 'repaired'
  | 'manual-review-required'
  | 'passed';

/**
 * Standard finding generated by the Accessibility Scanner.
 * Integration point for Member 2 (Bhavya).
 */
export interface AccessibilityFinding {
  id: string;
  ruleId: string;
  ruleTitle: string;
  category: FindingCategory;
  severity: SeverityLevel;
  explanation: string;
  affectedCode: string;
  selector?: string;
  status: FindingStatus;
  suggestedFix?: string;
  isDeterministicFixable: boolean;
}

/**
 * High-level summary metrics of a scan run.
 */
export interface ScanSummary {
  totalIssues: number;
  warningsCount: number;
  passedCount: number;
  criticalCount: number;
  seriousCount: number;
  moderateCount: number;
  minorCount: number;
  score: number; // 0 - 100
}

/**
 * Result returned by the Accessibility Scanner for a given HTML payload.
 * Integration point for Member 2 (Bhavya).
 */
export interface ScanResult {
  id: string;
  rawHtml: string;
  timestamp: string;
  summary: ScanSummary;
  findings: AccessibilityFinding[];
}

/**
 * Individual deterministic fix record applied to an element.
 */
export interface RepairItem {
  id: string;
  findingId: string;
  ruleId: string;
  appliedFix: string;
  safeDeterministic: boolean;
  originalSnippet: string;
  repairedSnippet: string;
}

/**
 * Result returned by the Safe Deterministic Repair Engine.
 * Integration point for Member 3 (Sravani).
 */
export interface RepairResult {
  id: string;
  scanId: string;
  originalHtml: string;
  repairedHtml: string;
  repairedCount: number;
  unresolvedCount: number;
  repairs: RepairItem[];
  timestamp: string;
}

export type VerificationStatus = 'verified' | 'partially-verified' | 'failed' | 'pending';

/**
 * Verification result comparing post-repair re-scan against original scan.
 * Integration point for Member 2 (Bhavya).
 */
export interface VerificationResult {
  id: string;
  repairId: string;
  originalScore: number;
  repairedScore: number;
  originalIssueCount: number;
  remainingIssueCount: number;
  resolvedCount: number;
  isVerified: boolean;
  status: VerificationStatus;
  resolvedFindings: AccessibilityFinding[];
  remainingFindings: AccessibilityFinding[];
  timestamp: string;
}

/**
 * Audit session record for Cloud Firestore persistence.
 * Integration point for Member 3 (Sravani).
 */
export interface AuditHistoryRecord {
  id: string;
  timestamp: string;
  htmlSnippetTitle?: string;
  originalScore: number;
  finalScore: number;
  originalIssueCount: number;
  repairedIssueCount: number;
  remainingIssueCount: number;
  status: 'completed' | 'in-progress';
}

/**
 * Legacy compatibility interfaces
 * Preserved to avoid breaking existing scaffolding or demo components.
 */
export interface AccessibilityIssue {
  id: string;
  ruleId: string;
  description: string;
  severity: SeverityLevel;
  selector: string;
  suggestedFix?: string;
  isResolved: boolean;
}

export interface AuditReport {
  id: string;
  targetUrl: string;
  score: number;
  totalIssues: number;
  resolvedIssues: number;
  timestamp: string;
  issues: AccessibilityIssue[];
}

export interface FeatureHighlight {
  id: string;
  title: string;
  description: string;
  iconName: string;
  badge?: string;
}
